# Workflow for caching iOS build packages (yarn + cocoapods)
# Note this always re-caches, which can take a while
# Also run by build workflow but this allows for caching separately, since cache is not updated on build errors

name: Cache iOS

on:
  workflow_dispatch:

jobs:
  cache:
    name: Cache iOS production packages for later use by build job
    environment: production

    runs-on: macos-latest

    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: cache cocoapods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: yarn install
        run: yarn install --force

      - name: pod install
        run: |
          cd ios
          pod install --deployment --clean-install
